
name: INTEGRATION

on:
  workflow_run:
    workflows: [ "Android Debug CI" ]
    types:
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Echo test
        run: echo ======test======

