name: Android Release CI

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Echo Tag
        run: |
          rtt=$(git describe --tags `git rev-list --tags --max-count=1`)
          rt=${rtt#*v}
          echo === $rt ===
        env:
          curr_tag: ${{ rt }}

      - name: Test
        if: contains(${{steps.env.curr_tag}}, 'video')
        run: |
          echo "=== this is video tag " ${{steps.env.curr_tag}} ===
