name: Android Release CI

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Echo Tag
        id: get_tag
        run: |
          rtt=$(git describe --tags `git rev-list --tags --max-count=1`)
          rt=${rtt#*v}
          echo === $rt ===
          echo "curr_tag=$rt" >> $GITHUB_ENV

      - name: Test
        if: ${{contains(env.curr_tag, 'video')}}
        run: |
          echo "=== this is video tag " ${{ env.curr_tag }} ===
