name: Android Release CI

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Echo Tag
        run: |
          rtt=$(git describe --tags `git rev-list --tags --max-count=1`)
          rt=${rtt#*v}
          is_video=contains($rt, 'video')
          echo "::set-env name=video::$is_video"

      - name: Test
        if: env.video
        run: |
          echo 'this is video tag'
