name: Android Release CI

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Echo Tag
        run: |
          rtt=$(git describe --tags `git rev-list --tags --max-count=1`)
          rt=${rtt#*v}
        env:
          curr_tag: $rt

      - name: Test
        if: contains(${{jobs.build.steps.env.tag}}, 'video')
        run: |
          echo 'this is video tag'
