name: iOS pod CI

on:
  push:
    tags:
      - '*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: install rdoc
      run: sudo gem install rdoc
    - name: install fir
      run: sudo gem install fir-cli
