name: Android Debug CI

on:
  push:
    paths-ignore: # 有時候不想要改個文档也触发 github actions
      - '**.md'
      - 'LICENSE'
    tags-ignore:  # 屏蔽掉发release打tag事件
      - '*'
    branches:
      - '*'

env:
  IOT_WECOM_CID_ROBOT_KEY: ${{ secrets.IOT_WECOM_CID_ROBOT_KEY }}

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./test.txt') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Fix App Version
        run: |
          rtt=$(git describe --tags --match "*video*" --abbrev=0 HEAD)
          echo $rtt =====
          rttt=$(git describe --tags --match "v[0-9]*" --abbrev=0 HEAD)
          echo $rttt ----main_latest_tag
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          echo $VERSION
      - name: Download r10e NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r10e-linux-x86_64.zip
          unzip android-ndk-r10e-linux-x86_64.zip
          cd android-ndk-r10e
          pwd
      - name: Sleep for 5 seconds
        run: sleep 5s
        shell: bash
      - name: Test success
        if: ${{ success() }}
        run: |
          echo success!!!
          echo ${{ github.event.repository.name }}
          bash .github/scripts/send_result_to_wecom.sh ${{ github.event.repository.name }} success
      - name: Test fail
        if: ${{ failure() }}
        run: |
          echo fail!!!
          bash .github/scripts/send_result_to_wecom.sh ${{ github.event.repository.name }} fail
