name: iOS pod CI

on:
  push:
    branches:
      - '*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: install fir
      run: |
        sudo apt-get install ruby2.7.0 ruby2.7.0-dev
        ruby -v
        sudo gem install fir-cli
