name: iOS pod CI

on:
  push:
    branches:
      - '*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: install fir
      run: |
        sudo gem update --system
        sudo gem install fir-cli
