name: Android Debug CI

on:
  push:
    paths-ignore: # 有時候不想要改個文档也触发 github actions
      - '**.md'
      - 'LICENSE'
    tags-ignore:  # 屏蔽掉发release打tag事件
      - '*'
    branches:
      - '*'

env:
  IOT_SONATYPE_USERNAME: ${{ secrets.IOT_SONATYPE_USERNAME }}
  IOT_SONATYPE_PASSWORD: ${{ secrets.IOT_SONATYPE_PASSWORD }}
  IOT_RELEASE_KEYSTORE_PASSWORD: ${{ secrets.IOT_RELEASE_KEYSTORE_PASSWORD }}
  GPG_DECRYPT_PASSPHRASE: ${{ secrets.GPG_DECRYPT_PASSPHRASE }}
  IOT_GPG_KEYNAME: ${{ secrets.IOT_GPG_KEYNAME }}
  IOT_GPG_PASSPHRASE: ${{ secrets.IOT_GPG_PASSPHRASE }}
  IOT_GITHUB_ACCESS_TOKEN: ${{ secrets.IOT_GITHUB_ACCESS_TOKEN }}

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fix App Version
        run: |
          rtt=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo $rtt
