name: Android Debug CI

on:
  push:
    paths-ignore: # 有時候不想要改個文档也触发 github actions
      - '**.md'
      - 'LICENSE'
    tags-ignore:  # 屏蔽掉发release打tag事件
      - '*'
    branches:
      - '*'

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
      - name: Fix App Version
        run: |
          rtt=$(git describe --tags --match "*video*" --abbrev=0 HEAD)
          echo $rtt =====
          rttt=$(git describe --tags --match "v[0-9]*" --abbrev=0 HEAD)
          echo $rttt ----main_latest_tag
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          echo $VERSION
      - name: Sleep for 30 seconds
        run: sleep 30s
        shell: bash
