name: iOS pod CI

on:
  push:
    paths-ignore:
      - '**.md'
      - 'LICENSE'

jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: zip test
        run: |
          mkdir test
          touch test/test.txt
          zip -r test.zip test
      - name: Upload aar to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test
          path: |
            test.zip
      - name: Upload xp2p to Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: test.zip
          asset_name: test.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#     - name: update ruby
#       run: |
#         sudo add-apt-repository ppa:brightbox/ruby-ng
#         sudo apt-get update
#         sudo apt-get purge --auto-remove ruby
#         sudo apt-get install ruby2.7 ruby2.7-dev
#     - name: install fir
#       run: |
#         ruby -v
#         sudo gem install fir-cli
