name: iOS pod CI

on:
  push:
    paths-ignore: # 有時候不想要改個文档也触发 github actions
      - '**.md'
      - 'LICENSE'
    tags-ignore:  # 屏蔽掉发release打tag事件
      - '*'
    branches:
      - '*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: |
          rtt=$(git describe --tags `git rev-list --tags --grep video --max-count=1`)
          rt=${rtt#*v}
          echo === $rt ===
#       - name: zip test
#         run: |
#           mkdir test
#           touch test/test.txt
#           zip -r test.zip test
#       - name: Upload aar to Artifacts
#         uses: actions/upload-artifact@v2
#         with:
#           name: test
#           path: |
#             test.zip
#       - name: Get release
#         if: startsWith(github.event.ref, 'refs/tags')
#         id: get_release
#         uses: bruceadams/get-release@v1.2.2
#         env:
#           GITHUB_TOKEN: ${{ github.token }}
#       - name: Upload Release Asset
#         if: startsWith(github.event.ref, 'refs/tags')
#         id: upload-release-asset 
#         uses: actions/upload-release-asset@v1
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         with:
#           upload_url: ${{ steps.get_release.outputs.upload_url }}
#           asset_path: ./test.zip
#           asset_name: test.zip
#           asset_content_type: application/zip
#     - name: update ruby
#       run: |
#         sudo add-apt-repository ppa:brightbox/ruby-ng
#         sudo apt-get update
#         sudo apt-get purge --auto-remove ruby
#         sudo apt-get install ruby2.7 ruby2.7-dev
#     - name: install fir
#       run: |
#         ruby -v
#         sudo gem install fir-cli
