name: Android CI

on:
  push:
    paths-ignore: # 有時候不想要改個文档也触发 github actions
      - '**.md'
      - 'LICENSE'
    tags-ignore:  # 屏蔽掉发release打tag事件
      - '*'
    branches:
      - '*'

env:
  TEST: ${{ secrets.TEST }}

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - run: |
          ls
      - name: Test_0
        run: |
          sh .github/scripts/test.sh
      - name: Test_1
        run: |
          cd iot-version
          ls
  
