name: Android Debug CI

on:
  push:
    paths-ignore: # 有時候不想要改個文档也触发 github actions
      - '**.md'
      - 'LICENSE'
    tags-ignore:  # 屏蔽掉发release打tag事件
      - '*'
    branches:
      - '*'

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fix App Version
        run: |
          rtt=$(git describe --tags --match "*videoo*" --abbrev=0 HEAD)
          echo $rtt =====
          rttt=$(git describe --tags --match "v[0-9]*" --abbrev=0 HEAD)
          echo $rttt -----
