name: iOS pod CI

on:
  push:
    paths-ignore:
      - '**.md'
      - 'LICENSE'

jobs:
  build-and-deploy:
    runs-on: macos-10.15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Deploy to CocoapodsPre
      run: |
        sh .github/scripts/test.sh
    - name: Set output
      id: vars
      run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

    - name: Extract tag name
      id: tag
      uses: actions/github-script@0.2.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          return context.payload.ref.replace(/\/refs\/tags\//, '');
    - name: Echo
      run: |
        echo ${{ steps.tag.outputs.result }}
        echo ============1
        git tag
        echo ============2
        git describe --tags `git rev-list --tags --max-count=1`
        echo ============3
        git describe --tags --abbrev=0


