name: iOS pod CI

on:
  push:
    paths-ignore:
      - '**.md'
      - 'LICENSE'

jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: zip test
        run: |
          mkdir test
          touch test/test.txt
          zip -r test.zip test
      - name: Upload aar to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test
          path: |
            test.zip
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./test.zip
          asset_name: test.zip
          asset_content_type: application/zip
#     - name: update ruby
#       run: |
#         sudo add-apt-repository ppa:brightbox/ruby-ng
#         sudo apt-get update
#         sudo apt-get purge --auto-remove ruby
#         sudo apt-get install ruby2.7 ruby2.7-dev
#     - name: install fir
#       run: |
#         ruby -v
#         sudo gem install fir-cli
