name: iOS pod CI

on:
  push:
    tags:
      - '*'

jobs:
  build-and-deploy:
    runs-on: macos-10.15
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Deploy to CocoapodsPre
      run: |
        sh .github/scripts/test.sh
    - name: Set output
      id: vars
      run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

    - name: Check output
      run: |
        echo ===1=${{ steps.vars.outputs.short_ref }}
        echo ===2=${{ github.head_ref }}
        echo ===3=$(echo $GITHUB_REF | cut -d'/' -f 3)

    - name: Get Branch
      run: |
        raw=$(git branch -r --contains ${{ github.ref }})
        branch=${raw##*/}
        echo "BRANCH=$branch" >> $GITHUB_ENV
        echo ===4=$(branch)
     - run: echo ${{ env.BRANCH }}

