name: Windows Debug CI

on:
  push:
    paths-ignore: # 有時候不想要改個文档也触发 github actions
      - '**.md'
      - 'LICENSE'
    tags-ignore:  # 屏蔽掉发release打tag事件
      - '*'
    branches:
      - '*'

env:
  IOT_WECOM_CID_ROBOT_KEY: ${{ secrets.IOT_WECOM_CID_ROBOT_KEY }}

jobs:
  build:
    runs-on: windows-2019
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.8
      with:
        cmake-version: '3.17.0'
    - name: build libenet
      if: startsWith(github.event.ref, 'refs/heads')
      run: |
        VERSION=$(echo "${{ github.ref }}")
        echo $VERSION
        export GIT_BRANCH_IMAGE_VERSION=$VERSION
      shell: pwsh
      env:
        GIT_ACCESS_TOKEN: ${{ secrets.IOT_GITHUB_ACCESS_TOKEN }}
        PROVISIONING_PASSWORD: ${{ secrets.GPG_DECRYPT_PASSPHRASE }}
